"""ml/evaluate.py - the harness: three tasks, every backend that can run.

    python -m ml.evaluate
    python -m ml.evaluate --data ml/data/tms_synthetic_bookings.json

Reads the synthetic world, splits it BY TIME, trains every backend in
ml/models.py that has its dependencies, scores three tasks, and writes
ml/reports/evaluation.json and ml/reports/evaluation.md.

The split is the part that earns trust, so it is strict:

  * The first ~70% of the timeline trains, the rest tests - evaluation mimics
    predicting a future the model has not seen, which is the only future a
    deployed model ever gets. A random split would let the model train on
    Thursday's episode and be quizzed on Wednesday's.
  * No episode may straddle the boundary. Disruption episodes touch many
    bookings, and a model that saw three bookings caught in a strike would be
    scored on the fourth booking in the SAME strike - memorisation dressed as
    prediction. Bookings tangled in a boundary-straddling episode are dropped,
    the report says how many, and the harness ASSERTS the train and test
    episode sets are disjoint.

Backends whose dependencies are missing are skipped with the reason printed
and recorded - here, tabpfn skips (no torch, and the weights download is
blocked); on a machine without scikit-learn, the sklearn rows skip too and
the stdlib baselines plus the shipped rules engine still report.

Metrics are implemented in the standard library on purpose, so a zero-install
machine can still score the baselines: accuracy, macro-F1 and a confusion
table for the action model; MAE and P90 absolute error for the delay model;
ROC-AUC (rank-based) and the Brier score for the breach model.

And the part that must never get lost: every number this file produces is a
score against a SYNTHETIC world - see the preamble it writes at the top of
both reports. The numbers say nothing about real freight and must never
appear on the product pages.
"""

import argparse
import json
from pathlib import Path

from ml import models

REPORTS_DIR = Path(__file__).resolve().parent / "reports"
DEFAULT_DATA = Path(__file__).resolve().parent / "data" / "tms_synthetic_bookings.json"

TRAIN_FRACTION = 0.7

# Written verbatim at the top of both reports. If you are editing this, you
# are probably about to make a claim the project cannot back - read
# ml/README.md first.
HONESTY_PREAMBLE = (
    "EVERY NUMBER IN THIS REPORT IS SYNTHETIC-WORLD PERFORMANCE. The dataset "
    "is generated by ml/synth.py: bookings, disruptions and outcomes all come "
    "from a structural model with latent variables and noise, and the labels "
    "are the generator's realized outcomes - not any policy's opinion, and "
    "not real freight history. A model scored here has learned the simulated "
    "world, nothing more. These numbers say NOTHING about accuracy on real "
    "shipments - that would need real TMS history, which sits on the far side "
    "of the integration wall - and they must NEVER appear on the product "
    "pages (static/), in the README's pitch, or in any demo narration. They "
    "exist to compare model families against each other and against the "
    "shipped rules engine, inside a world we control end to end."
)


# ---------------------------------------------------------------------------
# Loading and the time split
# ---------------------------------------------------------------------------


def load_world(path: Path) -> dict:
    try:
        with open(path, encoding="utf-8") as handle:
            return json.load(handle)
    except FileNotFoundError:
        raise SystemExit(
            f"No dataset at {path}.\n"
            f"Generate one first:  python -m ml.synth --bookings 6000 --seed 7")


def split_by_time(world: dict):
    """Train on the early world, test on the late one, drop the tangled edge.

    Returns (train, test, info). Every record keeps its outcome block here -
    the harness needs it for labels - and it is stripped before records are
    handed to any model.
    """
    bookings = sorted(world["bookings"], key=lambda b: (b["facts"]["decided_on"], b["id"]))
    decided = [b["facts"]["decided_on"] for b in bookings]
    # The cut sits 70% of the way through the DECISION timeline, day-wise,
    # so it is a date in the world - not an index into the book - and the
    # same cut applies to bookings and episodes alike.
    cut_date = decided[min(len(decided) - 1, round(len(decided) * TRAIN_FRACTION))]

    episode_side = {e["episode_id"]: ("train" if e["started_on"] < cut_date else "test")
                    for e in world["episodes"]}

    train, test, dropped = [], [], 0
    for booking in bookings:
        sides = {episode_side[e["episode_id"]]
                 for e in booking["facts"]["active_episodes"]}
        booking_side = "train" if booking["facts"]["decided_on"] < cut_date else "test"
        if sides and sides != {booking_side}:
            # This booking is tangled in an episode that lives on the other
            # side of the cut. Scoring it would leak the episode across the
            # boundary, so it sits the evaluation out.
            dropped += 1
            continue
        (train if booking_side == "train" else test).append(booking)

    train_episodes = {e["episode_id"] for b in train
                      for e in b["facts"]["active_episodes"]}
    test_episodes = {e["episode_id"] for b in test
                     for e in b["facts"]["active_episodes"]}
    straddlers = train_episodes & test_episodes
    assert not straddlers, (
        f"Episodes straddle the time split: {sorted(straddlers)} - the split "
        f"is leaking, and every score it produces is inflated.")

    info = {"cut_date": cut_date, "train": len(train), "test": len(test),
            "dropped_straddling_bookings": dropped,
            "train_episodes": len(train_episodes), "test_episodes": len(test_episodes)}
    return train, test, info


def strip_outcomes(records):
    """What models are allowed to see: the booking without its answer key."""
    return [{k: v for k, v in r.items() if k != "outcome"} for r in records]


# ---------------------------------------------------------------------------
# Metrics - stdlib on purpose, so the baselines score with zero installs
# ---------------------------------------------------------------------------


def accuracy(y_true, y_pred):
    return sum(1 for t, p in zip(y_true, y_pred) if t == p) / len(y_true)


def macro_f1(y_true, y_pred):
    labels = sorted(set(y_true) | set(y_pred))
    scores = []
    for label in labels:
        tp = sum(1 for t, p in zip(y_true, y_pred) if t == label and p == label)
        fp = sum(1 for t, p in zip(y_true, y_pred) if t != label and p == label)
        fn = sum(1 for t, p in zip(y_true, y_pred) if t == label and p != label)
        precision = tp / (tp + fp) if tp + fp else 0.0
        recall = tp / (tp + fn) if tp + fn else 0.0
        scores.append(2 * precision * recall / (precision + recall)
                      if precision + recall else 0.0)
    return sum(scores) / len(scores)


def confusion(y_true, y_pred, labels):
    return {t: {p: sum(1 for a, b in zip(y_true, y_pred) if a == t and b == p)
                for p in labels}
            for t in labels}


def mae(y_true, y_pred):
    return sum(abs(t - p) for t, p in zip(y_true, y_pred)) / len(y_true)


def p90_abs_error(y_true, y_pred):
    errors = sorted(abs(t - p) for t, p in zip(y_true, y_pred))
    return errors[min(len(errors) - 1, round(0.9 * (len(errors) - 1)))]


def roc_auc(y_true, scores):
    """Rank-based AUC (the Mann-Whitney statistic), ties averaged. Returns
    None when the test set has only one class - an AUC of nothing is more
    honest than a made-up 0.5."""
    positives = sum(y_true)
    negatives = len(y_true) - positives
    if not positives or not negatives:
        return None
    order = sorted(range(len(scores)), key=lambda i: scores[i])
    ranks = [0.0] * len(scores)
    index = 0
    while index < len(order):
        tied_end = index
        while (tied_end + 1 < len(order)
               and scores[order[tied_end + 1]] == scores[order[index]]):
            tied_end += 1
        average_rank = (index + tied_end) / 2 + 1
        for position in range(index, tied_end + 1):
            ranks[order[position]] = average_rank
        index = tied_end + 1
    positive_rank_sum = sum(r for r, t in zip(ranks, y_true) if t)
    return (positive_rank_sum - positives * (positives + 1) / 2) / (positives * negatives)


def brier(y_true, scores):
    return sum((s - t) ** 2 for t, s in zip(y_true, scores)) / len(y_true)


# ---------------------------------------------------------------------------
# The run
# ---------------------------------------------------------------------------


def score(task, y_true, y_pred):
    if task == "action":
        return {"accuracy": round(accuracy(y_true, y_pred), 4),
                "macro_f1": round(macro_f1(y_true, y_pred), 4),
                "confusion": confusion(y_true, y_pred, models.ACTION_LABELS)}
    if task == "delay":
        return {"mae_days": round(mae(y_true, y_pred), 3),
                "p90_abs_error_days": round(p90_abs_error(y_true, y_pred), 3)}
    auc = roc_auc(y_true, y_pred)
    return {"roc_auc": round(auc, 4) if auc is not None else None,
            "brier": round(brier(y_true, y_pred), 4)}


def _environment() -> dict:
    """Recorded in the report because the sklearn numbers can shift across
    releases even though the dataset itself is byte-reproducible per seed."""
    import platform
    env = {"python": platform.python_version()}
    try:
        import sklearn
        env["scikit_learn"] = sklearn.__version__
    except ImportError:
        env["scikit_learn"] = None
    return env


def evaluate(world: dict) -> dict:
    train, test, split_info = split_by_time(world)
    train_visible = strip_outcomes(train)
    test_visible = strip_outcomes(test)

    results = {}
    for task, registry in models.MODELS.items():
        y_train = [models.target_for(task, r) for r in train]
        y_test = [models.target_for(task, r) for r in test]
        results[task] = {}
        for name, factory in registry.items():
            try:
                model = factory()
            except models.DependencyMissing as exc:
                print(f"[{task}] {name}: SKIPPED - {str(exc).splitlines()[0]}")
                results[task][name] = {"skipped": str(exc)}
                continue
            model.fit(train_visible, y_train)
            predictions = model.predict(test_visible)
            results[task][name] = score(task, y_test, predictions)
            headline = {k: v for k, v in results[task][name].items() if k != "confusion"}
            print(f"[{task}] {name}: {headline}")
    return {"honesty": HONESTY_PREAMBLE, "world": world["world"],
            "split": split_info, "environment": _environment(),
            "results": results}


# ---------------------------------------------------------------------------
# Reports
# ---------------------------------------------------------------------------


def _fmt(value):
    return "-" if value is None else (f"{value:.3f}" if isinstance(value, float) else str(value))


def render_markdown(report: dict) -> str:
    world = report["world"]
    split = report["split"]
    results = report["results"]
    lines = [
        "# Model evaluation - synthetic world only",
        "",
        f"> {report['honesty']}",
        "",
        f"Dataset: {world['bookings']} bookings over {world['weeks']} weeks, "
        f"seed {world['seed']} - regenerate it exactly with "
        f"`python -m ml.synth --bookings {world['bookings']} --seed {world['seed']}`. "
        f"Scored on Python {report.get('environment', {}).get('python', '?')}, "
        f"scikit-learn {report.get('environment', {}).get('scikit_learn') or 'not installed'} "
        f"- the dataset is byte-reproducible from its seed, but sklearn numbers "
        f"can drift across library releases.",
        "",
        f"Time split at {split['cut_date']}: {split['train']} bookings train, "
        f"{split['test']} test, {split['dropped_straddling_bookings']} dropped "
        f"because a disruption episode straddled the boundary "
        f"({split['train_episodes']} train episodes, {split['test_episodes']} "
        f"test episodes, zero shared - asserted, not assumed).",
        "",
    ]

    lines += ["## Action model - reroute / hold / no-action", "",
              "| backend | accuracy | macro-F1 |", "|---|---|---|"]
    for name, r in results["action"].items():
        if "skipped" in r:
            lines.append(f"| {name} | skipped | skipped |")
        else:
            lines.append(f"| {name} | {_fmt(r['accuracy'])} | {_fmt(r['macro_f1'])} |")
    best = _best(results["action"], "accuracy", higher=True)
    if best:
        lines += ["", f"Confusion table for `{best}` (rows = truth, columns = predicted):", ""]
        table = results["action"][best]["confusion"]
        lines.append("| truth \\ predicted | " + " | ".join(models.ACTION_LABELS) + " |")
        lines.append("|---|" + "---|" * len(models.ACTION_LABELS))
        for truth in models.ACTION_LABELS:
            lines.append(f"| {truth} | " + " | ".join(
                str(table[truth][p]) for p in models.ACTION_LABELS) + " |")
    lines.append("")

    lines += ["## Delay model - days late on the do-nothing path", "",
              "| backend | MAE (days) | P90 abs error (days) |", "|---|---|---|"]
    for name, r in results["delay"].items():
        if "skipped" in r:
            lines.append(f"| {name} | skipped | skipped |")
        else:
            lines.append(f"| {name} | {_fmt(r['mae_days'])} | {_fmt(r['p90_abs_error_days'])} |")
    lines.append("")

    lines += ["## Breach model - probability the deadline breaks", "",
              "| backend | ROC-AUC | Brier |", "|---|---|---|"]
    for name, r in results["breach"].items():
        if "skipped" in r:
            lines.append(f"| {name} | skipped | skipped |")
        else:
            lines.append(f"| {name} | {_fmt(r['roc_auc'])} | {_fmt(r['brier'])} |")
    lines.append("")

    skipped = sorted({name for task in results.values()
                      for name, r in task.items() if "skipped" in r})
    if skipped:
        lines += ["## Skipped backends", ""]
        seen = set()
        for task in results.values():
            for name, r in task.items():
                if "skipped" in r and name not in seen:
                    seen.add(name)
                    lines.append(f"**{name}**\n")
                    lines += [f"    {line}" for line in r["skipped"].splitlines()]
                    lines.append("")

    lines += _plain_language_reading(results)
    return "\n".join(lines) + "\n"


def _best(task_results, metric, higher=True):
    scored = {n: r[metric] for n, r in task_results.items()
              if "skipped" not in r and r.get(metric) is not None}
    if not scored:
        return None
    return (max if higher else min)(scored, key=scored.get)


def _plain_language_reading(results) -> list[str]:
    """The closing section, written for the repo owner, who does not code.

    Every NUMBER and every direction-of-error claim below is computed from the
    results dict, so those can never contradict the tables above. The causal
    explanations (why the rules engine trails, where the noise comes from) are
    descriptions of the current generator calibration - regenerate the world
    with different NOISE/TYPE_PARAMS and reread them before trusting them."""
    lines = ["## What this means, in plain language", ""]

    action = results["action"]
    if "skipped" not in action.get("gbm", {"skipped": True}) and "skipped" not in action.get("majority", {"skipped": True}):
        gbm = action["gbm"]["accuracy"]
        majority = action["majority"]["accuracy"]
        lines.append(
            f"On the reroute/hold/do-nothing call, always answering \"do nothing\" "
            f"is right {majority:.0%} of the time in this simulated world - most "
            f"bookings are fine, there as here. The best trained model gets "
            f"{gbm:.0%}. The gap between those two numbers is what learning is "
            f"actually worth on this task. The shortfall from 100% is by "
            f"construction: the generator injects noise no observer is shown - "
            f"how hard a storm bites, whether a strike settles tomorrow - so a "
            f"model scoring near-perfectly here would be a bug, not a triumph.")
        if "skipped" not in action.get("rules", {"skipped": True}):
            rules = action["rules"]["accuracy"]
            table = action["rules"]["confusion"]
            acted = [l for l in models.ACTION_LABELS if l != "no-action"]
            # Which way the rules engine is wrong is measured, not asserted -
            # a report that described a direction the table contradicts would
            # be this repo's hard-coded "live" chip all over again.
            over_alert = sum(table["no-action"][p] for p in acted)
            under_alert = sum(table[t]["no-action"] for t in acted)
            caught = sum(table[t][p] for t in acted for p in acted)
            missed = under_alert
            lines.append("")
            lines.append(
                f"The rules engine the product actually ships scores {rules:.0%} "
                f"here. It asks one timing question this harness surfaced the "
                f"need for - whether an episode will still be standing when the "
                f"vessel actually reaches the chokepoint (timing_factor in "
                f"src/route_advisor.py, asked only when the record carries the "
                f"facts to answer it). What remains of the gap is everything "
                f"else the learners weigh that a fixed rule cannot: how hard "
                f"each episode type tends to bite, what each carrier tends to "
                f"add, and what the instruments were reading.")
            if caught + missed:
                direction = (
                    f"they acted on {over_alert} bookings the world left alone and "
                    f"stayed quiet on {under_alert} it did not"
                    + (", which is the safer way round to be wrong"
                       if over_alert >= under_alert else
                       " - the more dangerous way round to be wrong, and worth"
                       " noting before trusting this calibration"))
                lines.append("")
                lines.append(
                    f"In exchange the rules caught {caught} of the {caught + missed} "
                    f"bookings that genuinely needed action, where \"always do "
                    f"nothing\" catches none. On this test set {direction}.")
            best_name = _best(action, "accuracy")
            best_table = action.get(best_name, {}).get("confusion")
            if best_name and best_name != "rules" and best_table and (caught + missed):
                best_caught = sum(best_table[t][p] for t in acted for p in acted)
                lines.append("")
                lines.append(
                    f"One number accuracy hides: of those {caught + missed} bookings "
                    f"that needed action, the rules moved on {caught} and "
                    f"{best_name} - the accuracy winner - moved on {best_caught}. "
                    f"A model can be right more often by acting rarely, and a "
                    f"policy can miss less by acting constantly; which error "
                    f"costs more is a desk decision, not a modelling one, so "
                    f"neither headline number settles the choice on its own.")

    delay = results["delay"]
    if "skipped" not in delay.get("gbm", {"skipped": True}) and "skipped" not in delay.get("mean", {"skipped": True}):
        lines.append("")
        lines.append(
            f"On \"how late will this booking actually run\", guessing the "
            f"historical average is off by {delay['mean']['mae_days']:.1f} days "
            f"on a typical booking; the best model is off by "
            f"{delay['gbm']['mae_days']:.1f}. That is the difference between a "
            f"number you can put in a customer email and one you cannot.")

    breach = results["breach"]
    if "skipped" not in breach.get("gbm", {"skipped": True}):
        auc = breach["gbm"]["roc_auc"]
        lines.append("")
        lines.append(
            f"On \"will the deadline break\", the best model's ROC-AUC is "
            f"{auc:.2f}: show it two bookings, one that will breach and one that "
            f"will not, and it puts the riskier one first {auc:.0%} of the time. "
            f"That ranking is what an approval queue would sort by, so the "
            f"person works the most urgent booking first.")

    lines += ["",
              "None of these numbers transfer to real freight. They show the "
              "PIPELINE works - features, split, baselines, honest labels - and "
              "they rank model families against each other inside a controlled "
              "world. The day real TMS history exists, this same harness runs "
              "unchanged and produces numbers that mean something operationally; "
              "until then, these stay in ml/reports/ and out of every page, "
              "pitch and demo.", ""]
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Evaluate every available backend against the synthetic world.")
    parser.add_argument("--data", default=str(DEFAULT_DATA),
                        help="dataset produced by python -m ml.synth")
    args = parser.parse_args()

    world = load_world(Path(args.data))
    print(f"Evaluating against {args.data} "
          f"({world['world']['bookings']} bookings, seed {world['world']['seed']})\n")
    report = evaluate(world)

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    json_path = REPORTS_DIR / "evaluation.json"
    with open(json_path, "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=1, ensure_ascii=False)
        handle.write("\n")
    md_path = REPORTS_DIR / "evaluation.md"
    with open(md_path, "w", encoding="utf-8") as handle:
        handle.write(render_markdown(report))

    print(f"\nWrote {json_path}")
    print(f"Wrote {md_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
